### ISSUE TITLE
[3rd party] Add custom test case, that requires config and is focused on external packages testing

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#5478]
Now the `AbstractTestCase` is optimized both for core and 3rd party packages (with lot of magic). Performance optimizations crashes with UX and it's mess for both sides :)

It will be better to have 2 test cases:

- 1st for internal Rector rule, that load all the rules in container at once
- 2nd for 3rd party packages, that will have clear API to implement and easy to use and extend

## Todo

- [x] Decouple `AbstractCommunityTestCase` from `AbstractTestCase`
- [x] Remove magical `rector.php` autoload
- [x] Promote config loading approach
- [x] Update on `master` & then verify on real project - https://github.com/sabbelasichon/typo3-rector, cc @sabbelasichon 
- [x] Create Rector rule to switch from `getRectorClass()` to `getConfigFilePath()`

**Comment by TomasVotruba** [comment]
## Todo

- [ ] Update & verify on https://github.com/sabbelasichon/typo3-rector, cc @sabbelasichon

**Comment by sabbelasichon** [comment]
@TomasVotruba Let me know what to do and i will be your test candidate.

**Comment by TomasVotruba** [comment]
Resolved
