### ISSUE TITLE
[Meta] Add Rector release command to update CHANGELOG.md headlines

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#5663]
## Todo

- [x] add monorepo builder
- [x] add `composer.json` command - https://github.com/symplify/symplify/blob/5241c9056c2c82c6530d3905ed6738e7453d9ec7/composer.json#L258
- [x] add workers to `monorepo-builder.php`, see https://github.com/symplify/symplify/blob/5241c9056c2c82c6530d3905ed6738e7453d9ec7/monorepo-builder.php#L30-L38, just these:

```php
	$services->set(UpdateReplaceReleaseWorker::class);
    $services->set(AddTagToChangelogReleaseWorker::class);
    $services->set(TagVersionReleaseWorker::class);
    $services->set(PushTagReleaseWorker::class);
    $services->set(PushNextDevReleaseWorker::class);
```
