### ISSUE TITLE
[Meta] [PHP 7.1 do 5.6] Plan to downgrade PHP

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector#6079]
After [Rector 0.10 with PHP 7.1 downgraded code](https://getrector.org/blog/2021/03/22/rector-010-released-with-php71-support), we want to go even deeper. Next stop is PHP 5.6, as that's where most legacy projects are stuck. Right before the huge wall of PHP 7.0 :)

This is meta issue to reference downgrade rules. To kick of with few.

# From PHP 7.1 to PHP 7.0 - 

RFC links: https://wiki.php.net/rfc#php_71

- [x] Downgrade Symmetric array destructuring to list() function ( https://github.com/rectorphp/rector/blob/main/rules/DowngradePhp71/Rector/Array_/SymmetricArrayDestructuringToListRector.php  )
- [x] Downgrade class constant visibility ( https://github.com/rectorphp/rector/blob/main/rules/DowngradePhp71/Rector/ClassConst/DowngradeClassConstantVisibilityRector.php ) 
- [x] Remove the iterable pseudo type params and returns, add @param and @return tags instead ( https://github.com/rectorphp/rector/blob/main/rules/DowngradePhp71/Rector/FunctionLike/DowngradeIterablePseudoTypeDeclarationRector.php )
- [x] Remove the nullable type params, add @param tags instead ( https://github.com/rectorphp/rector/blob/main/rules/DowngradePhp71/Rector/FunctionLike/DowngradeNullableTypeDeclarationRector.php )
- [x] Remove `void` type - https://wiki.php.net/rfc/void_return_type ( https://github.com/rectorphp/rector/blob/main/rules/DowngradePhp71/Rector/FunctionLike/DowngradeVoidTypeDeclarationRector.php )
- [x] Downgrade negative string offset to strlen ( https://github.com/rectorphp/rector/blob/main/rules/DowngradePhp71/Rector/String_/DowngradeNegativeStringOffsetToStrlenRector.php  ) 
- [x] Downgrade single one | separated to multi catch exception(https://github.com/rectorphp/rector/blob/main/rules/DowngradePhp71/Rector/TryCatch/DowngradePipeToMultiCatchExceptionRector.php)
- [x] Downgrade keys in list ( https://github.com/rectorphp/rector/pull/6170 )

# From PHP 7.0 to PHP 5.6

RFC link: https://wiki.php.net/rfc#php_70

- [x] Remove anonymous classes https://wiki.php.net/rfc/anonymous_classes
- [x] Remove scalar type declarations - https://wiki.php.net/rfc/scalar_type_hints_v5 ( https://github.com/rectorphp/rector/blob/main/rules/DowngradePhp70/Rector/FunctionLike/DowngradeTypeDeclarationRector.php )
- [x] Remove strict_types declaration - https://wiki.php.net/rfc/scalar_type_hints_v5
- [x] Remove Null coalescing - https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op
- [x] Change Spaceship to invokable anonymous function with if equal, then return ternary ( https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.spaceship-op )
- [x] Change define array constant to const ( https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.define-array )
- [x] Move array options in session_start to before statement ini_set ( https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.session-options )

**Comment by TomasVotruba** [comment]
@samsonasik Could you complete list with most wide-spread features in PHP world?

**Comment by samsonasik** [comment]
I will try

**Comment by samsonasik** [comment]
✔️  Remove void type seems implemented at https://github.com/rectorphp/rector/blob/main/rules/DowngradePhp71/Rector/FunctionLike/DowngradeVoidTypeDeclarationRector.php

**Comment by samsonasik** [comment]
✔️ Remove scalar type declarations seems implemented at https://github.com/rectorphp/rector/blob/main/rules/DowngradePhp70/Rector/FunctionLike/DowngradeTypeDeclarationRector.php

**Comment by TomasVotruba** [comment]
@samsonasik Could you update the issue description with links to these rules? So we have it one place

**Comment by samsonasik** [comment]
@TomasVotruba updated.

**Comment by samsonasik** [comment]
@TomasVotruba for Remove anonymous classes, do you think it need to create a new dedicated class and create the instance of it before remove the anonymous class?

**Comment by TomasVotruba** [comment]
I think so :+1:

**Comment by lulco** [comment]
From PHP 7.1 to PHP 7.0 - remove nullable types

**Comment by samsonasik** [comment]
@lulco that already in DowngradeNullableTypeDeclarationRector https://github.com/rectorphp/rector/blob/main/rules/DowngradePhp71/Rector/FunctionLike/DowngradeNullableTypeDeclarationRector.php

I will update the list.

**Comment by samsonasik** [comment]
@lulco list updated.

**Comment by TomasVotruba** [comment]
There was a tool that downgraded most common features of PHP 7 to PHP 5 - https://github.com/spatie/7to5 for inspiration

**Comment by samsonasik** [comment]
@TomasVotruba scoped to 7.0 process got error on adding phpstan-src 

```bash
composer require phpstan/phpstan-src --ignore-platform-reqs

Using version ^0.12.85 for phpstan/phpstan-src

./composer.json has been updated

PHP Fatal error:  Cannot declare class RectorPrefix20210505\Composer\InstalledVersions, because the name is already in use in /home/runner/work/rector/rector/remote-repository-php70/vendor/composer/InstalledVersions.php on line 7

Fatal error: Cannot declare class RectorPrefix20210505\Composer\InstalledVersions, because the name is already in use in /home/runner/work/rector/rector/remote-repository-php70/vendor/composer/InstalledVersions.php on line 7

Error: Process completed with exit code 255.
```

ref https://github.com/rectorphp/rector/runs/2506182264?check_suite_focus=true#step:19:9

Do you have idea how to solve it?

**Comment by leoloso** [comment]
I think you can avoid scoping `InstalledVersions.php` without any harm, and avoiding this issue.

**Comment by samsonasik** [comment]
@leoloso ok, let's try on https://github.com/rectorphp/rector/pull/6335

**Comment by samsonasik** [comment]
@leoloso it seems still error https://github.com/rectorphp/rector/runs/2507401040#step:19:10 , while it actually already changed in `vendor/composer/package-versions-deprecated/src/PackageVersions/Versions.php` : 

https://github.com/rectorphp/rector-prefixed-php70/blob/main/vendor/composer/package-versions-deprecated/src/PackageVersions/Versions.php#L6

**Comment by leoloso** [comment]
But you're handling it through a patcher, which operates after doing the scoping. I was suggesting to completely skip scoping that file.

That's what I did my project when I had the same issue as you have now, and now it works well ([source](https://github.com/leoloso/PoP/blob/76b81a4403c19be7e3512025f6a23eddace77e36/ci/scoping/scoper-graphql-api.inc.php#L90-L94)):

```php
'files-whitelist' => [
    convertRelativeToFullPath('vendor/composer/InstalledVersions.php'),
],
```

**Comment by samsonasik** [comment]
@leoloso thank you. @TomasVotruba the phpstan-src versioning php requirement seems different with phpstan's. It can't be solved with ignore platform reqs as it has different packages requirement, do you have idea how to solve it? Thank you.

**Comment by TomasVotruba** [comment]
The phpstan-src must be downgraded to PHP 7.1

**Comment by samsonasik** [comment]
Yes, but getting phpstan-src from php 7.3 is not possible, even with ignore platform reqs due different packages requirements, ref:

https://github.com/phpstan/phpstan-src/blob/40d93a147556aa696d1aa6c0e1dad9c7530820e3/composer.json#L8-L12

Do we need php 7.4 ?

**Comment by TomasVotruba** [comment]
> Do we need php 7.4 ? 

I think so  :+1: the version Rector runs downgrade in is not really relevant. It can be PHP 8 too

**Comment by samsonasik** [comment]
@TomasVotruba the phpstan-src is now included, but on downgrading process, it got error:

```bash
Run sh build/downgrade-rector-php70.sh rector-build-php70

[NOTE] Running downgrade in 'rector-build-php70' directory

PHP Fatal error:  Uncaught Nette\MemberAccessException: Cannot read an undeclared property PHPStan\DependencyInjection\Configurator::$parameters. in /home/runner/work/rector/rector/vendor/nette/utils/src/Utils/ObjectHelpers.php:31

Stack trace:
#0 /home/runner/work/rector/rector/vendor/nette/utils/src/SmartObject.php(76): Nette\Utils\ObjectHelpers::strictGet()
#1 /home/runner/work/rector/rector/vendor/phpstan/phpstan-src/src/DependencyInjection/Configurator.php(42): Nette\Bootstrap\Configurator->__get()
#2 /home/runner/work/rector/rector/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(252): PHPStan\DependencyInjection\Configurator->loadContainer()
#3 /home/runner/work/rector/rector/vendor/phpstan/phpstan-src/src/DependencyInjection/ContainerFactory.php(102): Nette\Bootstrap\Configurator->createContainer()
#4 /home/runner/work/rector/rector/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php(43): PHPStan\DependencyInjection\ContainerFactory->create()
#5 /tmp/rector/cache/Container7O4zmPC/HttpKernelRect in /home/runner/work/rector/rector/vendor/nette/utils/src/Utils/ObjectHelpers.php on line 31

Fatal error: Uncaught Nette\MemberAccessException: Cannot read an undeclared property PHPStan\DependencyInjection\Configurator::$parameters. in /home/runner/work/rector/rector/vendor/nette/utils/src/Utils/ObjectHelpers.php:31
Stack trace:
#0 /home/runner/work/rector/rector/vendor/nette/utils/src/SmartObject.php(76): Nette\Utils\ObjectHelpers::strictGet()
#1 /home/runner/work/rector/rector/vendor/phpstan/phpstan-src/src/DependencyInjection/Configurator.php(42): Nette\Bootstrap\Configurator->__get()
#2 /home/runner/work/rector/rector/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(252): PHPStan\DependencyInjection\Configurator->loadContainer()
#3 /home/runner/work/rector/rector/vendor/phpstan/phpstan-src/src/DependencyInjection/ContainerFactory.php(102): Nette\Bootstrap\Configurator->createContainer()
#4 /home/runner/work/rector/rector/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php(43): PHPStan\DependencyInjection\ContainerFactory->create()
#5 /tmp/rector/cache/Container7O4zmPC/HttpKernelRect in /home/runner/work/rector/rector/vendor/nette/utils/src/Utils/ObjectHelpers.php on line 31
Error: Process completed with exit code 255.
```

It seems some code are different between in `phpstan/phpstan` and `phpstan/phpstan-src`, another example is current error:

```bash
PHP Fatal error:  Interface 'PHPStan\BetterReflection\SourceLocator\Type\SourceLocator' not found
```

in https://github.com/rectorphp/rector-prefixed-php70/runs/2500555629#step:4:4 which not exists in https://github.com/phpstan/phpstan-src

**Comment by TomasVotruba** [comment]
Btw, just a tip. Instead of pushing to `main` and waiting for CI, you can use local script to get feedback much faster.

I did the same for building rector-prefixed in `full_build.sh`

**Comment by TomasVotruba** [comment]
It might be easier to downgrade phpstan/phpstan-src first as standalone project. And when that is ok add it to Rector.
Scoping PHPStan has own `scoper.php` that might be needed 1:1  https://github.com/phpstan/phpstan-src/blob/master/compiler/build/scoper.inc.php

**Comment by samsonasik** [comment]
@TomasVotruba thank you, I may need to create `full_build_php70.sh` then for excluding the dependencies that cause conflicts, ref:

https://github.com/rectorphp/rector/blob/19be81179615bd074e9cc7c304746a57a4ea32a9/.github/workflows/build_scoped_rector_php70.yaml#L37-L48

That removal need to be executing first as `composer/xdebug-handler` and `phpstan/phpstan` are in `require`.

I will check the phpstan's scoper.inc.php if that works to scope phpstan-src first.

**Comment by TomasVotruba** [comment]
We've just relased Sponsorware initiative https://getrector.org/blog/rector-for-php56-native

**Comment by TomasVotruba** [comment]
Untill the sponsorware treshold #1 is met, this issue is not a priority.
